### PR TITLE
Add pathsToPush and cachixArgs

### PR DESCRIPTION
**Pull request by ncfavier**
Give more control to the user over exactly what is pushed and how.

Fixes https://github.com/cachix/cachix-action/issues/74, fixes https://github.com/cachix/cachix-action/issues/88.

Tested on my repo.

### CODE REVIEW

**Comment by ncfavier** [comment]
@domenkozar could you take a look at this?

**Comment by NobbZ** [comment]
Would this require explicit listing of store pathes, or can I specify the `$(pwd)/result*` or an equivalent expression?

**Comment by ncfavier** [comment]
You would indeed have to list every path explicitly. Globbing could probably be implemented by unquoting an expansion somewhere.

**Comment by NobbZ** [comment]
Every store path? Or does the symlink approach work at least?

**Comment by ncfavier** [comment]
Cachix will happily follow symlinks and relative paths, yes.

**Pull request merged**
