### PR TITLE
Add nixBuildArgs parameter

### PR DESCRIPTION
**Pull request by Gerschtli**
Hey,

I added a new parameter for the action called `nixBuildArgs`. This adds arbitrary arguments to the `nix-build` command like for example `--keep-going`, `--show-trace` or `--argstr foo bar`.

Resolves https://github.com/cachix/cachix-action/issues/24 in a more general way.

### CODE REVIEW

**Comment by domenkozar** [comment]
Would be nice to add a single usage to tests so I can be sure I won't break this feature in the future.

**Comment by Gerschtli** [comment]
Added a test.

**Comment by Gerschtli** [comment]
I think the builds are failing because a pull request triggered build does not contain the signingKey.

**Comment by domenkozar** [comment]
Thanks!

**Pull request merged**
