### PR TITLE
RFC: save cache on post

### PR DESCRIPTION
**Pull request by zimbatm**
This breaks backward-compatibility and changes the action to be more in line with what I would expect this action to do. Which is to only setup the cache, and then upload all the extra build closures at the end of the job. It's a bit like `actions/cache` in that sense.

### CODE REVIEW

**Comment by zimbatm** [comment]
For some reason I get the following error when using this branch:
```
Error: Cannot find module '@actions/core'
```
I don't know why yet.

**Comment by domenkozar** [comment]
One of the design goals in mind that I had is that you can push to multiple caches in a single job. Typically some to a public cache and some to a private cache.

Maybe that was fighting more against the design of actions given that they've introduced the post hook and that `actions/cache` uses it that way.

Probably https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds is a better solution to such requirement.

The reason you get that error is that you have to commit `node_modules` when action is released. I was planning to rewrite it to bash as all the other actions.

**Comment by zimbatm** [comment]
> One of the design goals in mind that I had is that you can push to multiple caches in a single job. Typically some to a public cache and some to a private cache.

Ok, I need to think more about that because it's not a scenario I had in mind.

Is the idea that the private cache would include everything that is in the public cache + some private bits? With the idea that internal clients can only consume from the private cache and avoid the overhead of multiple queries inherent from setting up multiple caches at the same time?

**Comment by zimbatm** [comment]
@domenkozar how about this:

If the action has `postPush: true` then the post action is enabled *and* `skipBuild` is also assumed to be true. The action stays backward-compatible. The only downside is that the post-build step will now appear on all of the jobs even if they don't use that feature.

**Comment by zimbatm** [comment]
As an example: here we want to run `nixops deploy --build-only` to make sure that the deployment will work: https://github.com/nix-community/infra/pull/20/commits/69cf40d21675ec04011c248a9fa3d64211434e22

**Pull request merged**
